name: MOPAC 
run-name: Test Workflow
on:
  push:
    branches: "*"

jobs:
  myjob:
    runs-on: ubuntu-22.04
    steps:
       - name: Clone repository
         uses: actions/checkout@v4
        
       - name: Build docker image
         run: docker build -t dulcetorres/mopac .

       - name: Run mopac
         run: docker run --rm -v $(pwd):/input dulcetorres/mopac formic_acid.mop

       - name: Print results
         run: cat formic_acid.out
