name: MOPAC 
run-name: Test Workflow
on:
  push:
    branches: "*"

jobs:
  myjob:
    runs-on: ubuntu-latest
    steps: 
      - name: Pull image
        run: docker pull dulcetorres/mopac

        
      - name: Run mopac
        run: docker run --rm -v $(pwd):/input dulcetorres/mopac formic_acid.mop

        
      - name: Print results
        run: cat formic_acid.out
